BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `locations` (
	`id`	INT,
	`name`	TEXT
);
INSERT INTO `locations` VALUES (16,'Melilla');
INSERT INTO `locations` VALUES (17,'Ceuta');
INSERT INTO `locations` VALUES (18,'Zaragoza');
INSERT INTO `locations` VALUES (19,'Zamora');
INSERT INTO `locations` VALUES (20,'Valladolid');
INSERT INTO `locations` VALUES (21,'Valencia/València');
INSERT INTO `locations` VALUES (22,'Toledo');
INSERT INTO `locations` VALUES (23,'Teruel');
INSERT INTO `locations` VALUES (24,'Tarragona');
INSERT INTO `locations` VALUES (25,'Soria');
INSERT INTO `locations` VALUES (26,'Sevilla');
INSERT INTO `locations` VALUES (27,'Segovia');
INSERT INTO `locations` VALUES (28,'Santa Cruz de Tenerife');
INSERT INTO `locations` VALUES (29,'Salamanca');
INSERT INTO `locations` VALUES (30,'La Rioja');
INSERT INTO `locations` VALUES (31,'Pontevedra');
INSERT INTO `locations` VALUES (32,'Las Palmas');
INSERT INTO `locations` VALUES (33,'Palencia');
INSERT INTO `locations` VALUES (34,'Ourense');
INSERT INTO `locations` VALUES (35,'Navarra');
INSERT INTO `locations` VALUES (36,'Murcia');
INSERT INTO `locations` VALUES (37,'Málaga');
INSERT INTO `locations` VALUES (38,'Madrid');
INSERT INTO `locations` VALUES (39,'Lugo');
INSERT INTO `locations` VALUES (40,'Lleida');
INSERT INTO `locations` VALUES (41,'León');
INSERT INTO `locations` VALUES (42,'Jaén');
INSERT INTO `locations` VALUES (43,'Huesca');
INSERT INTO `locations` VALUES (44,'Huelva');
INSERT INTO `locations` VALUES (45,'Guadalajara');
INSERT INTO `locations` VALUES (46,'Granada');
INSERT INTO `locations` VALUES (47,'Girona');
INSERT INTO `locations` VALUES (48,'Gipuzkoa');
INSERT INTO `locations` VALUES (49,'Cuenca');
INSERT INTO `locations` VALUES (50,'A Coruña');
INSERT INTO `locations` VALUES (51,'Córdoba');
INSERT INTO `locations` VALUES (52,'Ciudad Real');
INSERT INTO `locations` VALUES (53,'Castellón/Castelló');
INSERT INTO `locations` VALUES (54,'Cantabria');
INSERT INTO `locations` VALUES (55,'Cádiz');
INSERT INTO `locations` VALUES (56,'Cáceres');
INSERT INTO `locations` VALUES (57,'Burgos');
INSERT INTO `locations` VALUES (58,'Bizkaia');
INSERT INTO `locations` VALUES (59,'Barcelona');
INSERT INTO `locations` VALUES (60,'Illes Balears');
INSERT INTO `locations` VALUES (61,'Badajoz');
INSERT INTO `locations` VALUES (62,'Ávila');
INSERT INTO `locations` VALUES (63,'Asturias');
INSERT INTO `locations` VALUES (64,'Araba/Álava');
INSERT INTO `locations` VALUES (65,'Almería');
INSERT INTO `locations` VALUES (66,'Alicante/Alacant');
INSERT INTO `locations` VALUES (67,'Albacete');
COMMIT;
